import { Geist, Geist_Mono } from "next/font/google";
import styles from "./page.module.css";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import { ShoppingCartOutlined } from "@ant-design/icons";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header className={styles.header} >
          <div className="logo">
            <Image src="/1images.jpg" alt="logo" width={70} height={70} />
          </div>
          <nav className={styles.navigation}>
            <ul className={styles.navigationList}>
              <li className={styles.navigationItem}><Link href={"/"}>Главная</Link></li>
              <li className={styles.navigationItem}><Link href={"/about"}>О нас</Link></li>
              <li className={styles.navigationItem}><Link href={"/sales"}>Акции</Link></li>
            </ul>

            <Link className={styles.navigationItem} href={"/cart"}><ShoppingCartOutlined /></Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
